### PR TITLE
Package test and release pipelines

### PR DESCRIPTION
**Pull request by norkator**
This is for later use. Merging this does nothing. Pipeline is triggered from release events /tags.

To publish package, @SKR301 needs to make npm account and get npm_token which is inserted here at github in repository environment variables or secrets.

Package json is needed for package release and also with test case running if this has any in any point.

### CODE REVIEW

**Review by SKR301 — CHANGES_REQUESTED** [review]
Added some tests to the repository, can you make changes to your PR accordingly so that tests are executed for every commit

**Comment by norkator** [comment]
Screenshot 2021-11-18 at 16 44 45

Interesting @SKR301, heres a puzzle for you, why this test fails on Github linux based container but not locally, at least on my Mac.

**Comment by norkator** [comment]
Maybe some timezone.. etc.. issue?

**Comment by SKR301** [comment]
Could be...
I have it as one of the issue in repo.
Need to make timezone-proof tests

**Review by SKR301 — COMMENTED** [review]
Awesome work...

**Pull request merged**
